settings:
  mqtt_everest_prefix: "ev"

active_modules:
  ev_manager:
    module: JsEvManager
    config_module:
      connector_id: 1
      auto_enable: false
      auto_exec: true
      auto_exec_commands: sleep 1;iec_wait_pwr_ready;sleep 1;draw_power_regulated 16,3;sleep 30;unplug
    connections:
      ev_board_support:
        - module_id: yeti_driver
          implementation_id: ev_board_support
      slac:
        - module_id: slac
          implementation_id: ev
      ev:
        - module_id: iso15118_car
          implementation_id: ev
  yeti_driver:
    module: JsYetiEvSimulator
  slac:
    module: JsSlacEvSimulator
  iso15118_car:
    module: PyEvJosev
    config_module:
      device: auto
      supported_ISO15118_2: true
      tls_active: true
      is_cert_install_needed: true
  system:
    module: System
